### ISSUE TITLE
Verification of the calculated trajectory

### ISSUE THREAD

**Issue by kamilk00** [Qubi0-0/drone_position_based_on_aruco#3]
Verify the correctness of the calculated camera position. If you find any errors, try to correct them.

**Comment by djurowski** [comment]
to do this, from the first frame check calculate camera point, and check distance between marker 3 and camera point, marker 1 and marker 4. Distances should be always equal, solving equations (symbolically) should result in obtaining correct camera position every frame. complex numbers are involved.
you can also do it the simple way, using constant x, y, z modifications, losing accuracy.
good luck @Qubi0-0
